stages:
  - build
  - config

build_faser_daq:
  stage: build
  image: gitlab-registry.cern.ch/faser/docker/daq:master
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - ls
    - pwd
    - source setup.sh
    - export BOOST_ROOT_DIR=/opt/lcg/Boost/1.70.0-eebf1/x86_64-centos7-gcc8-opt 
    - export BOOST_VERSION=1.70
    - mkdir -p build 
    - cd build
    - cmake3 ../
    - make -j8
    
validate_configs:
  stage: config
  image: gitlab-registry.cern.ch/faser/docker/daq:master
  allow_failure: True
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - pip3 install jsonref
  script:
    - cd scripts
    - source runConfigCheck.sh 