stages:
  - build
  - deploy

build_faser_daq:
  stage: build
  image: gitlab-registry.cern.ch/faser/docker/daq:master
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - ls
    - pwd
    - source setup.sh
    - export BOOST_ROOT_DIR=/opt/lcg/Boost/1.70.0-eebf1/x86_64-centos7-gcc8-opt 
    - export BOOST_VERSION=1.70
    - mkdir -p build 
    - cd build
    - cmake3 ../
    - make -j8

build_mkdocs:
  stage: build
  image: python:3.8-buster
  script:
    - apt-get update -y
    - apt-get install -y doxygen
    - pip install -r requirements.txt
    - mkdir public
    - mkdocs build --verbose --site-dir public
  artifacts:
    paths:
      - public
    expire_in: 1 week

deployment_mkdocs:
  stage: deploy
  dependencies: [build_mkdocs]
  image: python:3.8-buster
  only:
    - master
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
    - deploy-eos
  before_script: []
  after_script: []