stages:
  - build 
  - config
  - deploy

build_faser_daq:
  stage: build
  needs: []
  image: gitlab-registry.cern.ch/faser/docker/daq:master
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - ls
    - pwd
    - source setup.sh
    - export BOOST_ROOT_DIR=/opt/lcg/Boost/1.70.0-eebf1/x86_64-centos7-gcc8-opt 
    - export BOOST_VERSION=1.70
    - mkdir -p build 
    - cd build
    - cmake3 ../
    - make -j8
    
check_license:
  stage: build
  image: gitlab-registry.cern.ch/faser/docker/daq:master
  script:
    - python scripts/CheckLicense.py -directory . -extensions cpp cxx h hpp py 
  allow_failure: True

build_mkdocs:
  stage: build
  needs: []
  image: python:3.8-buster
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -qq update 
    - apt-get -qq install krb5-user libpam-krb5
    - apt-get -qq clean
    - apt-get update -y
    - apt-get install -y doxygen
    - pip install -r requirements.txt
    - mkdir public
    - echo $EOS_ACCOUNT_PASSWORD | kinit $EOS_ACCOUNT_USERNAME@CERN.CH
    - mkdocs build --verbose --site-dir public
  artifacts:
    paths:
      - public
    expire_in: 1 week

deployment_mkdocs:
  stage: deploy
  needs: [build_mkdocs]
  image: python:3.8-buster
  only:
    - master
    - add-mkdocs
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
    - deploy-eos
  before_script: []
  after_script: []

validate_configs:
  stage: config
  image: gitlab-registry.cern.ch/faser/docker/daq:master
  allow_failure: True
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - pip3 install jsonref
  script:
    - python scripts/CheckConfigs.py \
    - --directory configs \
    - --schemas   \
    - schemas/DigitizerReceiver.schema \
    - schemas/DigitizerMonitor.schema     \
    - schemas/DigitizerReceiver.schema     \
    - schemas/EmulatorMonitor.schema     \
    - schemas/EventBuilderFaser.schema     \
    - schemas/EventPlayback.schema     \
    - schemas/FileWriterFaser.schema     \
    - schemas/FrontEndEmulator.schema     \
    - schemas/FrontEndMonitor.schema     \
    - schemas/FrontEndReceiver.schema     \
    - schemas/TrackerMonitor.schema     \
    - schemas/TrackerReceiver.schema     \
    - schemas/TriggerGenerator.schema     \
    - schemas/TriggerMonitor.schema     \
    - schemas/TriggerRateMonitor.schema     \
    - schemas/TriggerReceiver.schema     \
    - --templates \
    - Templates/TLB.json \
    - Templates/TRB.json \
    - Templates/digitizer.json \
    - Templates/emulator.json \
    - Templates/fileWriter.json \
    - --configs   \
    - digitizerSciLab.json \
    - combinedEHN1.json \
    - --extras   \
    - Templates/test.json \
    - top.json \
    - Templates/TemplateModuleCfg0.json \
    - Templates/TemplateModuleCfg1.json \
    - Templates/TemplateModuleCfg2.json \
    - Templates/TemplateModuleCfg3.json \
    - Templates/TemplateModuleCfg4.json \
    - Templates/TemplateModuleCfg5.json \
    - Templates/TemplateModuleCfg6.json \
    - Templates/TemplateModuleCfg7.json \
    - Templates/eventBuilder.json \
    - Templates/monitor.json \
    - test.json \
    - RunTrackerEmulation_withMonitoring.json \
    - combinedSciLab.json \
    - current.json \
    - digitizerSciLab.json \
    - emulatorLocalhost.json \
    - emulatorLocalhost_templated.json \
    - emulatorLocalhost_withRefs.json \
    - grafana/faser_metrics.json                   \
    - schemas/.placeholder                   \
    - schemas/validation-schema.json                   \
    - Templates/top.json                   \
    - customized/host.json                   \
    - json-dump.py                   \
    - LUT_CombinedRun_Oct16.txt                   \
    - playback.json                   \
    - json-validate.py                   \
    - .placeholder                   
